-- Remove the "prospect" status from sponsors entirely.
-- Any existing prospect sponsors are converted to active, then the CHECK
-- constraint is rewritten to only allow 'active' or 'inactive'.

-- 1. Convert any existing prospect sponsors to active
UPDATE sponsors
SET status = 'active'
WHERE status = 'prospect';

-- 2. Drop the old CHECK constraint (name is auto-generated by Postgres
--    based on the table + column). Find and drop it dynamically.
DO $$
DECLARE
  constraint_name_var TEXT;
BEGIN
  SELECT conname INTO constraint_name_var
  FROM pg_constraint
  WHERE conrelid = 'public.sponsors'::regclass
    AND contype = 'c'
    AND pg_get_constraintdef(oid) ILIKE '%status%prospect%';

  IF constraint_name_var IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.sponsors DROP CONSTRAINT %I', constraint_name_var);
  END IF;
END $$;

-- 3. Add the new CHECK constraint allowing only active/inactive
ALTER TABLE public.sponsors
  ADD CONSTRAINT sponsors_status_check
  CHECK (status IN ('active', 'inactive'));
